name: CI

on:
  push:
    branches:
      - $default-branch
      
  pull_request:
    branches:
      - $default-branch

jobs:
  runTests:
    uses: akromio/.github/.github/workflows/nodejs-pi-ci.yaml@master
