name: CI

on:
  workflow_call:

jobs:
  runTests:
    name: Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [1.19]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Go ${{ matrix.node }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      
      - name: Linter
        run: |
          files=$(gofmt -l -w .)
          
          if [ "$files" != '' ]; then
            printf "The following files have been modified: ${files/$'\n'/, }\n"
            exit 1
          fi
      
      - name: Run tests
        run: |
          # (1) run tests
          error=0

          for module in ./modules/*; do
            coverage=$(go test $module/... -covermode count -coverprofile coverage | grep -v 'coverage: 100.0%' | cat)

            if [[ "$coverage" != "" ]]; then
              error=1
              go tool cover -func=coverage | grep -v "100.0%"
            fi
          done

          # (2) return exit code
          exit $error
