name: CI

on:
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash -e {0}

jobs:
  runTests:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16.x, 18.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install Gattuso
        uses: akromio/setup-gattuso@v1
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: gattuso r cov
